server:
  port: 8080

# 콘솔 ANSI 색상
spring:
  output:
    ansi:
      enabled: always

  # thymeleaf 설정
  thymeleaf:
    cache: false
    prefix: classpath:templates/views/

  # datasource 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db000?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: user000
    password: 1234

  # security
  security:
    user:
      name: user1     # 디폴트 security username
      password: 1234   #  password

    oauth2:
      client:
        registration:
          google:
            client-id: 658127517780-b97rhvcm5259jefs1vd3nouta94ge4ln.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

# MyBatis 매퍼(mapper) 파일 위치 설정
# src/main/resources 이하의 경로 지정
mybatis:
  mapper-locations: classpath:mapper/**/*.xml

openai:
  key: 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

app:
  oauth2:
    password: 1234

    kakao:
      client-id: cb42a69cfcd686165fba176daf2a938c
      redirect-uri: http://localhost:8080/oauth2/kakao/callback
      token-uri: https://kauth.kakao.com/oauth/token
      user-info-uri: https://kapi.kakao.com/v2/user/me


  pagination:
    page_rows: 10
    write_pages: 10
  upload:
    path: upload